### ISSUE TITLE
The parameter redirect_uri is required

### ISSUE THREAD

**Issue by zaasmi** [ashwin47/Net-Neutral#11]
The parameter redirect_uri is required

**Comment by veigas** [comment]
Do you get Image from user profile

**Comment by veigas** [comment]
you need to set login.php in your fb/dev/app dashboard under profilelogin

**Comment by zaasmi** [comment]
its solved but not get image from fb profile

**Comment by zaasmi** [comment]
http://cyberian.pk/profilepicframes/
