### ISSUE TITLE
The parameter redirect_uri is required

### ISSUE THREAD

**Issue by mhmdsohail** [ashwin47/Net-Neutral#14]
The parameter redirect_uri is required. Please help me to fix it.
<img width="1365" alt="screen shot 2016-08-25 at 4 29 11 pm" src="https://cloud.githubusercontent.com/assets/17947057/17969011/1b023b32-6ae1-11e6-93d2-dabb387d0914.png">

**Comment by ashwin47** [comment]
That is the $callback_url which you need to add in the cred.php file
