### ISSUE TITLE
i am receiving this error

### ISSUE THREAD

**Issue by stivdahdah** [ashwin47/Net-Neutral#18]
Facebook SDK returned an error: Cross-site request forgery validation failed. The "state" param from the URL and session do not match.

**Comment by ashwin47** [comment]
On which page ?

**Comment by stivdahdah** [comment]
After loging in and share update.

http://test.plixon.com/index.php

Do you take money if i want to install it on my hosting? 
Do you have skype?

**Comment by ashwin47** [comment]
Ping me @ashwinm on twitter
