### ISSUE TITLE
How you pass app registration in FB?

### ISSUE THREAD

**Issue by OleksandrKucherenko** [ashwin47/Net-Neutral#2]
%subj%

**Comment by rhnvrm** [comment]
@OleksandrKucherenko are you asking about the App ID and App Secret? If yes, see this from the readme.

> Please add a file named cred.php to the folder and add the following lines in them:
> 
> ```
> <?php
> $_YOUR_APP_ID = 'XYZ';
> $_YOUR_APP_SECRET = 'XYZ';
> ?>
> ```

**Comment by meedz** [comment]
Showing 'sorry this page is not found' from facebook..when i login

**Comment by rhnvrm** [comment]
Did you add the proper call back? if you are using on local host please use it as the callback

**Comment by ashwin47** [comment]
The problem is callback url which should be project specific.
resolving it.

**Comment by ashwin47** [comment]
Pushed fix please verify.

**Comment by meedz** [comment]
Guys Fixed the Problem Thank you
