### ISSUE TITLE
Im getting this error

### ISSUE THREAD

**Issue by aiyoob** [ashwin47/Net-Neutral#6]
Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookSDKException' with message 'Required "app_id" key not supplied in config and could not find fallback environment variable "FACEBOOK_APP_ID"' in /hsphere/local/home/stcb-sch/itclub.stcb.sch.lk/fbapp/Facebook/Facebook.php:133 Stack trace: #0 /hsphere/local/home/stcb-sch/itclub.stcb.sch.lk/fbapp/facebook_start.php(11): Facebook\Facebook->__construct(Array) #1 /hsphere/local/home/stcb-sch/itclub.stcb.sch.lk/fbapp/index.php(3): require('/hsphere/local/...') #2 {main} thrown in /hsphere/local/home/stcb-sch/itclub.stcb.sch.lk/fbapp/Facebook/Facebook.php on line 133

**Comment by ashwin47** [comment]
pull the latest.
