### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by notasensata** [ashwin47/Net-Neutral#7]
Hi there,
I am facing this 2 erros on main page: 

`Notice: Undefined variable: callback in /home/myserver/public_html/facebook/futebolfan/index.php on line 10`

`Notice: Undefined variable: bg_path in /home/myserver/public_html/facebook/futebolfan/index.php on line 38
class="bg">`

and also this when i click login:
`The parameter redirect_uri is required`

You say to to fill 'App domains' , 'Site URL' , 'Valid OAuth redirect URIs' accordingly. But in which file and where do we fill in this information ?

Regards
Jorge

**Comment by aiyoob** [comment]
The parameter redirect_uri is required
this is a problem comes with the code you need to add this code $callback_url    = 'yourhost/login.php'; to your index.php after $permissions 
and add $bg_path         = 'images/bg1.jpg';  after $callback code it will work.

**Comment by aiyoob** [comment]
Note :- make sure to get approval for 'user_posts','publish_actions' from facebook you can find at App Review Tab  then your web app can use by any user :+1:
